import 'package:food_ordering/common/model.dart';

class Globals {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Pizza   \n-  Fast Food",
      price: 140,
      image: "assets/images/pizza.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Burger  \n-   Fast Food",
      price: 25,
      image: "assets/images/burger.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Siomay   \n-  Fast Food",
      price: 20,
      image: "assets/images/momos.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Apple   \n-  Fruits",
      price: 50,
      image: "assets/images/apple.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Banana   \n-  Fruits",
      price: 30,
      image: "assets/images/banana.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Grapes   \n-  Fruits",
      price: 101,
      image: "assets/images/grapes.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "Guava   \n-  Fruits",
      price: 77,
      image: "assets/images/guava.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Orange   \n-  Fruits",
      price: 27,
      image: "assets/images/orange.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Pineapple  \n-   Fruits",
      price: 60,
      image: "assets/images/pineapple.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "Chocos   \n-  Grocery",
      price: 80,
      image: "assets/images/chocos.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Corn Flakes   \n-  Grocery",
      price: 90,
      image: "assets/images/corn_flakes.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Ice Cream   \n-  Grocery",
      price: 300,
      image: "assets/images/icecream.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Maggie   \n-  Grocery",
      price: 20,
      image: "assets/images/maggie.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "Tomato   \n-  Veges",
      price: 20,
      image: "assets/images/tomato.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Sandwitch   \n-  Fast Food",
      price: 45,
      image: "assets/images/sandwitch.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 16,
      name: "Broccoli   \n-  Veges",
      price: 15,
      image: "assets/images/broccoli.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 17,
      name: "Capsicum   \n-  Veges",
      price: 25,
      image: "assets/images/capsicum.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 18,
      name: "Carrot   \n-  Veges",
      price: 20,
      image: "assets/images/carrot.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 19,
      name: "Lottie Chocopie   \n-  Grocery",
      price: 30,
      image: "assets/images/lottie.png",
      quantity: 0,
      like: "false",
    ),
  ];
}